### ISSUE TITLE
Metaboxes

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework-4#1]
Which style would you prefer?

![screen shot 2013-11-21 at 22 44 04](https://f.cloud.github.com/assets/890963/1598613/2f4ca298-5339-11e3-9829-ee5d798b93fd.png)

OR

![screen shot 2013-11-21 at 22 44 17](https://f.cloud.github.com/assets/890963/1598614/31a8498e-5339-11e3-8684-13c306f72006.png)

**Comment by cyberwani** [comment]
WooCommerce is better, and in case of more tabs, it will work fine, without breaking tabs in horizontal.
