### ISSUE TITLE
Custom error message

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework-4#101]
If an API response has the key data.message, display the message instead of "unknown error".

If data.message_type, add the class of that message type to the notice. Possible message_types will be: info, warning, error, success.

If data.success = false, default to error (current styling).

Example API response:
```
{“success”:false,“data”:{“message”:“Please activate Redux.“}```

**Comment by alfredtakala** [comment]
In order to deal with all the cases, can you provide the message even on Success? I am afraid we currently don't return the message on Success case.

**Comment by dovy** [comment]
{“success”:true,“data”:{“message”:“Please activate Redux.“}```

**Comment by alfredtakala** [comment]
Please make sure to add `message_types`, though. That's more important than the message itself.
