### ISSUE TITLE
color_rgba field full transparent not working

### ISSUE THREAD

**Issue by theme-x** [reduxframework/redux-framework-4#109]
## Any Error Details (PHP/JavaScript)

When set the color full transparent its getting back to full color not transparent anymore, please have a look at the screen record for better understand https://streamable.com/5tq1rw

Here are my codes below
               array(
                    'id'       => 'top_head_bg_color',
                    'type'     => 'color_rgba',
                    'output'   => array( 
                    'background-color' => '.top_head',
                     ),
                    'title'    => esc_html__( 'Top header background color', 'text-domain' ),
                    'required'  => array( 'top_head', '=', '1' )
                ),

**Comment by dovy** [comment]
Fixed. Give it a try.  ;)
