### ISSUE TITLE
The Redux::set_extensions() method throws a warning

### ISSUE THREAD

**Issue by Tofandel** [reduxframework/redux-framework-4#11]
The warning being thrown 

`open_basedir restriction in effect. File(/plugins/redux-framework-4/ReduxCore/inc/extensions/index.php/class-redux-extension-extensions.php) is not within the allowed path(s)`

That's because the method is doing too much recursion, I can rewrite in a PR if needed

Also is it normal all those calls like 
```php
Redux_Functions_Ex::record_caller( $opt_name, debug_backtrace()[ array_search( __FUNCTION__, array_column( debug_backtrace(), 'function' ), true ) ]['file'] );
```

The double debug_backtrace is kinda hurting on performance.. And I checked, this function is not even registering them because of the strpos check.. Is it gonna be removed or is there gonna be a check on WP_DEBUG?

**Comment by dovy** [comment]
Pull request would be great.

@Tofandel this helpes the Redux Framework page that outlines "what is this". We're trying to track all the callers of Redux. Can you suggest a more performant method?

**Comment by Tofandel** [comment]
PR done

As for the record caller there is a way better method, it's the reflection class ;) 
I'll do another PR for that as well

**Comment by Tofandel** [comment]
Second PR done #13

**Comment by kprovance** [comment]
Added
