### ISSUE TITLE
Embedding Redux framework 4 in theme

### ISSUE THREAD

**Issue by tafsilva** [reduxframework/redux-framework-4#14]
Embedding Redux framework 4 in theme without installing plugin give error loading Redux files.

Old Redux framework work ok, but this new version doesn't work. I think something is wrong in_theme the folder path.

**// See if Redux is a plugin or not.**

for example:

`<link rel="stylesheet" id="redux-admin-theme-css-css" href="https://localhost/wordpress/wp-content/plugins/C:/xampp/htdocs/wordpress/wp-content/themes/my_theme/includes/redux-framework/ReduxCore/assets/css/colors/fresh/colors.css?ver=4.0.1.1.1551186467" type="text/css" media="all">`

Redux try to load files always in plugin folder `https://localhost/wordpress/wp-content/plugins/`

Full file path in 'url' `C:/xampp/htdocs/wordpress/wp-content/themes/my_theme/includes/redux-framework/ReduxCore/assets/css/colors/fresh/colors.css?ver=4.0.1.1.1551186467`

only for testing

changing **self::$url** to `get_template_directory_uri() . '/includes/redux-framework/ReduxCore/';`

works partially.

**Comment by kprovance** [comment]
Support hash please?  It was asked for and required.

**Comment by kprovance** [comment]
v4.0.1.2 should resolve this.  In the future, please respect our posting guidelines and include the support URL.  You'll save me a LOT of time.  Thanks!

**Comment by tafsilva** [comment]
Sorry. Get Support also doesn't work.

**support.php** line 18  **$_version**

`<span><?php printf( esc_html__( 'Version', 'redux-framework' ) . ' %s', esc_html( ReduxCore::$_version ) ); ?></span>`

I think it should be  **$version**

`<span><?php printf( esc_html__( 'Version', 'redux-framework' ) . ' %s', esc_html( ReduxCore::$version ) ); ?></span>`

Thanks and sorry again!
