### ISSUE TITLE
Backwards compatibility: incorrect theme usage of typography field output parameter prevents CSS output after upgrade to 4.x

### ISSUE THREAD

**Issue by FPCSJames** [reduxframework/redux-framework-4#140]
## Support Hash
N7q6mlfPjYYOUxIpSE3onnkjPdKwumqF91WDLkhcYiWMm7VG%2F3qQ5qrR%2B15lOce58N6aTz1GGJsOGDJf4W6XTA%3D%3D

## Steps to reproduce
0. Use an incorrectly-coded theme
1. Upgrade from 3.6.18 to 4.x
2. Observe lack of font CSS output

## Expected Behavior
Font CSS is output

## Actual Behavior
Font CSS is not output

## Additional information
Some themes have defined typography fields with the `output` parameter set to a string. Prior to the changes in 4.x in `Redux_Typography::output` that check if that parameter `is_array()` before processing, the options defined in these typography fields were output. Now, they do not. While this is absolutely the fault of the theme author, this may be fairly widespread, and it may warrant a small change to prevent backwards incompatibility for people who are using these themes, as has been done for other theme-caused bugs.

One possible fix, prior to the conditional on line 1014:

```
if( !empty ( $this->field['output'] ) && is_string( $this->field['output'] ) ) {
	$this->field['output'] = array( $this->field['output'] );
}
```

**Comment by dovy** [comment]
Oo, good call! What file do you add that to? I'll add it in.

**Comment by dovy** [comment]
IE, if you find which file to make the change I'll make the change immediately.

**Comment by FPCSJames** [comment]
> Oo, good call! What file do you add that to? I'll add it in.

redux-core/inc/fields/typography/class-redux-typography.php

**Comment by dovy** [comment]
Only for typography? We may want to put this in a higher level so it works with all field types. Let me test.

**Comment by FPCSJames** [comment]
I've only noticed this issue with typography so far, but it may happen elsewhere. It's definitely there where the breakage I've seen is occurring, because there wasn't an `is_array()` in that function as of 3.6.18, and now there is. At a quick glance, it looks like someother field types wouldn't have worked as of 3.6.18 with incorrect output definitions, because e.g. color requires a key and a value, not just a key, and goes through `Redux_Functions::parse_css()`.

Others that don't go through `Redux_Functions::parse_css()` but are output similarly to typography (e.g. background - the theme I'm working with has mis-defined its output param too) would call for the same kind of fix in their output methods.

**Comment by FPCSJames** [comment]
I tested with a background field that's got a string for output, and it inserted the background image as expected. It looks like it may just be typography.

**Comment by kprovance** [comment]
See if that 4.1.4.2 push fixes the typography issue.

**Comment by dovy** [comment]
Verified and pushed. 4.1.5.  :)
