### ISSUE TITLE
Google fonts loading issue with HTTPS websites

### ISSUE THREAD

**Issue by bgdcst** [reduxframework/redux-framework-4#141]
Latest plugin update (v4.1.4) doesn’t resolve this issue for https websites.

I’ve managed to fix this in **redux-core/classes/class-redux-output.php** on line 212 by changing:

`$protocol = ( ! empty( Redux_Core::$server['HTTPS'] ) && 'off' !== Redux_Core::$server['HTTPS'] || 443 === Redux_Core::$server['SERVER_PORT'] ) ? 'https:' : 'http:';`

to:

`$protocol = ( ! empty ( $_SERVER['HTTPS'] ) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443 ) ? "https:" : "http:";`

Changing line 840 on **redux-core/inc/fields/typography/class-redux-typography.php** now breaks Google fonts on both HTTP and HTTPS. 

On HTTP websites the link looks like this:
`http://localhost/my-websitehttp:https://fonts.googleapis.com/css?family=Open+Sans%3A400%7CJosefin+Sans%3A600%7CRoboto%3A700%2C500&#038;ver=1596124726`

On HTTPS websites it looks like this:
`https://www.my-website.com/http:https://fonts.googleapis.com/css?family=Playfair+Display%3A400`

Hope this helps with debugging.

Cheers!

**Comment by dovy** [comment]
This has been fixed. Sorry for the delay and I appreciate the report!
