### ISSUE TITLE
Select Ajax not working with custom Post Type

### ISSUE THREAD

**Issue by danielbarenkamp** [reduxframework/redux-framework-4#142]
Hi there,

great you just launched the v4 - looks good! We were the ones who donated 1000$ some (or more) months ago, you may remember. 

We see one problem with the new version and select field + custom post type + ajax.

Our configuration: 

```
                array(
                    'id'     =>'excludeProducts',
                    'type' => 'select',
                    'data' => 'posts',
                    'args' => array('post_type' => array('product'), 'posts_per_page' => -1),
                    'ajax' => true,
                    'multi' => true,
                    'title' => __('Exclude Products', 'woocommerce-pdf-catalog'), 
                    'subtitle' => __('Which products should be excluded in the PDF catalog.', 'woocommerce-pdf-catalog'),
                ),
```

It returns "no results" even if there are results:

<img width="803" alt="Bildschirmfoto 2020-07-31 um 08 15 23" src="https://user-images.githubusercontent.com/3169388/89006016-12fc2380-d306-11ea-929b-0974d2615644.png">

I guess it is because you are missing the custom post_type in the ajax call: 

<img width="487" alt="Bildschirmfoto 2020-07-31 um 08 15 27" src="https://user-images.githubusercontent.com/3169388/89006065-2effc500-d306-11ea-921d-8a24602a321d.png">

Can you add / fix that? That is super important, because if there is no AJAX, the admin panel is very slow, because it has to load ALL products. 

Without AJAX it works:
<img width="1104" alt="Bildschirmfoto 2020-07-31 um 08 10 30" src="https://user-images.githubusercontent.com/3169388/89006079-36bf6980-d306-11ea-82ca-3525277fbb2d.png">

**Comment by dovy** [comment]
Any way you can send me your code so I can test? Use wetransfer.com and send to dovy@redux.io. I'd really love to just debug in place so I can get to the bottom of this quickly. Thanks!

**Comment by danielbarenkamp** [comment]
@dovy Email with plugin sent now.

**Comment by dovy** [comment]
Awesome. I’ll get on it. :)

**Comment by danielbarenkamp** [comment]
Hey @dovy, do you have any update? I get multiple reports from users, that their sites are crashing :/

**Comment by dovy** [comment]
@danielbarenkamp can you hop on slack? I think I have it resolved, but I may be wrong.

**Comment by danielbarenkamp** [comment]
@danielbarenkamp I am located in Germany, kinda late here. But you can send code to me daniel.barenkamp@welaunch.io for testing :)

**Comment by dovy** [comment]
Wondering if you could do the same for me actually so I can test it directly in your code? haha. It would be much easier that way.

**Comment by danielbarenkamp** [comment]
@dovy I have sent you our woocommerce plugin via WeTransfer 4 days ago. Or what do you mean?
