### ISSUE TITLE
Metabox Lite - button_set and switch not displaying

### ISSUE THREAD

**Issue by STV11C** [reduxframework/redux-framework-4#15]
## Support Hash
https://support.redux.io/?id=RC3g7AbPOQ1P7ELCADQfR4%2BflXCdTSQdMuoc%2FvTGJbjl1OQwr6sQn4L7yjSdO4vGlz1LSBrv4yBLzFRrY00PZA%3D%3D

## Steps to reproduce
Add a 'button_set' or 'switch' type in Metabox Lite.

## Expected Behavior
For the 'button_set' or 'switch' to appear.

## Actual Behavior
Neither appeared.
Note that the other supported types appear (e.g. checkbox, radio, text, textarea, media, & color)

## Any Error Details (PHP/JavaScript)
No errors.

**Comment by kprovance** [comment]
They were removed from the lite version.   Sorry.

**Comment by STV11C** [comment]
Hi Kevin, ok thanks. Maybe just remove the supported types in the sample
config notes.

I've almost got a metabox lite option to work, however it seems the saved
value does not update across the whole site, but only within the page.
However the default value does update across the whole site.

Does that make sense?

Regards,
Stephan

**Comment by kprovance** [comment]
That's how it's supposed to work.  Metabox is per page/post/cpt.  Option panel is global.

**Comment by STV11C** [comment]
Hi Kevin, I understand that so I'll try to convey the issue better.
Please see screen shot attached.
Both these values (*has-hero* and *no-hero*) are using the same opt ID.
The top one (in header) does not update with the Saved value from the
Page... but it does display the Page's (the override MB Lite) 'default'
value.
Hope this helps.

Regards,
Stephan


[image: image.png]

**Comment by kprovance** [comment]
No screen shot came through.  I don't know how you are coding the front end.  Read this:  https://docs.reduxframework.com/extensions/metaboxes.  I know it's for the extension, but the same method for usage applies.

**Comment by STV11C** [comment]
Hi Kevin, I added the image and it's there now.

**Comment by kprovance** [comment]
See the docs page I sent you.  I have no idea how you are coding the front end.   You have to use the redux_post_meta function.

**Comment by STV11C** [comment]
I'm simply echoing the same value in two places in my template: E.g. 
`echo 'Show Hero Value in Header: ' . $gutenize_theme_options['opt-hero-page']; `
and
`echo 'Show Hero Value in Page: ' . $gutenize_theme_options['opt-hero-page']; `

I've read the docs page and will explore the redux_post_meta function. Cheers.

**Comment by kprovance** [comment]
Correct, this is because that array holds your global options.  The only way to access the option from the metaboxes is via the redux_post_meta function.  It looks first for the saved data from the page/post.  If it does not find it, it loads the default argument (don't set one to draw from the global option panel) and then from the global option panel (provided the IDs are the same).  It was written that way so the dev would not have to if/then iwth get_post_meta and then the option panel array.  Our function takes care of all of that.  Just pass in the opt_name, post_id and the id.

**Comment by kprovance** [comment]
The full docs for v4 aren't finished yet...otherwise this information would have been more easily accessible.  Dovy's working on them this week, but again, the docs for the extension apply for data retrieval.

**Comment by STV11C** [comment]
Thanks for the extra info Kevin :) 
Just one more thing in case I didn't articulate it well - the values in my screenshot _are not_ the global ones but from my actual page override. So the metabox lite values are working.
