### ISSUE TITLE
Warning Message in the ThemeOptions

### ISSUE THREAD

**Issue by wilokecom** [reduxframework/redux-framework-4#150]
## Any Error Details (PHP/JavaScript)
When a customer uses select post type features, it is causing https://i0.wp.com/documentation.wilcity.com/wp-content/uploads/2020/08/Screen-Shot-2020-08-25-at-09.02.33.png?resize=768%2C336&ssl=1
We can resolve this issue by replacing
`$args['post__in'] = $current_value;`
under redux-core -> inc -> classes -> Go to line 582 with
`$args['post__in'] = is_array($current_value) ? $current_value : [$current_value];`

**Comment by dovy** [comment]
Great catch. I've placed it in this repo. The fix will be in the next release hopefully due out today.
