### ISSUE TITLE
Theme Check plugin incompatibility

### ISSUE THREAD

**Issue by andrejarh** [reduxframework/redux-framework-4#158]
Just noticed: Theme Check plugin runs zero tests, when Redux 4 is present. 

Tested on WP 5.5.1, https://wordpress.org/plugins/theme-check/

**Comment by dovy** [comment]
Waa, really? That's odd... Hmm.

**Comment by dovy** [comment]
You can always just TGM the plugin...

**Comment by rosede** [comment]
Hi! I'm having an incompatibility issues with redux v4 after installing the new update.

<img width="1012" alt="Screen Shot 2020-09-22 at 10 40 51 AM" src="https://user-images.githubusercontent.com/16645930/93839644-28674b80-fcc0-11ea-98ec-222682f0d459.png">

I've tried to install the older version up to 4.0.1 but same issues appearing. Please help.
Thank you.

**Comment by mohammedeisa** [comment]
@rosede Your issue is not the same as the current one. Please open a new issue If you still have the same problem.

**Comment by kprovance** [comment]
This fix for this is available from this repo.  It'll be available on the wp.org repo for the July update.  Thanks!
