### ISSUE TITLE
I met with a problem on the latest version

### ISSUE THREAD

**Issue by webbudesign** [reduxframework/redux-framework-4#159]
I don't know what changed with the latest version, but 4.1.19 throwing an error on the **redux_post_meta** function.
4.1.18 working normally.

Error: 
`PHP Fatal error:  Uncaught Error: Call to a member function get_values() on null in /var/www/vhosts/xxx.com/xxx.com/wp-content/plugins/xxx/admin/newoptions/mextensions/metaboxes/extension_metaboxes.php:1360`

`$redux     = ReduxFrameworkInstances::get_instance( $opt_name );
 $metaboxes = $redux->extensions['metaboxes']; // This variable returning null.`

**Comment by dovy** [comment]
That is odd... Can you test if this exists in 4.1.18?

**Comment by webbudesign** [comment]
4.1.18 working normally. I am using it now.

**Comment by dovy** [comment]
~redux-core/inc/classes/class-redux-functions-ex.php
Can you remove this and let me know if the problem goes away?
```
			if ( empty( $new_class_name ) ) {
				return;
			}
```

**Comment by webbudesign** [comment]
Still the same. That code is not source of the problem.

**Comment by dovy** [comment]
Can you pass me your theme? I'll push a fix quick if I can test against your code.

dovy@redux.io

**Comment by webbudesign** [comment]
I sent you wp-admin information for my test server and page URL to see the problem. You can change any code by using the plugin editor.

Note, I think this will save your time to install the theme and quick setup, etc..

**Comment by dovy** [comment]
Great. Where can I see the error?

**Comment by dovy** [comment]
IE, what page?

**Comment by webbudesign** [comment]
I write the page URL on my email.

**Comment by dovy** [comment]
Ha, I totally missed that. My bad.

**Comment by dovy** [comment]
Found the location. Stepping through it.

**Comment by dovy** [comment]
Fixed. 4.1.20 is being pushed to .org right now.

**Comment by webbudesign** [comment]
Thank you very much.

**Comment by dovy** [comment]
Completely my fault. I did negative check on an if statement. My apologies.
