### ISSUE TITLE
URGENT!! Theme Error after installing new version4.1.20

### ISSUE THREAD

**Issue by rosede** [reduxframework/redux-framework-4#161]
Hi! I'm having an incompatibility issues with redux v4 after installing the new update.

<img width="1012" alt="Screen Shot 2020-09-22 at 10 40 51 AM" src="https://user-images.githubusercontent.com/16645930/93840034-87799000-fcc1-11ea-9608-50740cc20ee1.png">

I've tried to install the older version up to 4.0.1 but same issues appearing. Please help.
Thank you.

**Comment by dovy** [comment]
That's very odd! Do this: roll back to 3.6.18. Once you do that, send me a copy of your theme via wetransfer.com to dovy@redux.io and I'll take a look.

**Comment by rosede** [comment]
Thank s Dovy, I have followed your instruction and sent you the theme files. 
Please have a look. Thank you.

**Comment by dovy** [comment]
I'll get right on it and get back to you. Thanks!

**Comment by dovy** [comment]
Can you give it a file now? I think the issue should be resolved.

**Comment by dovy** [comment]
4.1.24 is about to land. This resolves the issue.
