### ISSUE TITLE
Warning if no theme exists (yes it's possible)

### ISSUE THREAD

**Issue by Tofandel** [reduxframework/redux-framework-4#17]
Warning: strpos(): Empty needle in /tmp/wordpress/wp-content/plugins/redux-framework-4/ReduxCore/inc/classes/class-redux-functions-ex.php on line 174

That's an easy fix:
`if ( strpos( $file_path, $real_path ) !== false ) {`

`if (  ! empty( $real_path ) && strpos( $file_path, $real_path ) !== false ) {`

**Comment by dovy** [comment]
I had just fixed that yesterday. Forgot to push. I’ll do it tomorrow. Thanks for the reminder.

**Comment by kprovance** [comment]
Pushed in v4.0.1.6
