### ISSUE TITLE
WBC importer extension not compatible with Redux framework 4.

### ISSUE THREAD

**Issue by andrejarh** [reduxframework/redux-framework-4#175]
Hi, 
I was trying to update old theme options which use Redux version 3 to version 4.
I am noticing there is an issue with the WBC importer extension, which was used for demo import. 
It causes PHP fatal error:

Fatal error: Uncaught Error: Class 'ReduxFramework_Extension_wbc_importer_extended' not found in /var/www/wp-content/plugins/recycle-plugin/admin/redux-framework/inc/classes/class-redux-functions-ex.php:325 Stack trace: #0 /var/www/wp-content/plugins/recycle-plugin/admin/redux-framework/inc/classes/class-redux-api.php(243): Redux_Functions_Ex::extension_compatibility(Object(ReduxFramework), '/var/www/wp-con...', 'ReduxFramework_...', 'ReduxFramework_...', 'wbc_importer') #1 /var/www/wp-content/plugins/recycle-plugin/admin/redux-framework/inc/classes/class-redux-api.php(208): Redux::load_extensions(Object(ReduxFramework)) #2 /var/www/wp-includes/class-wp-hook.php(287): Redux::loadExtensions(Object(ReduxFramework)) #3 /var/www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #4 /var/www/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #5 /var/www/wp-content/plugins/recycle-plugin/admin/redux-framework/inc/classes/class-redux-extensions.php(65): do_action('redux/extension...', Object(ReduxFramework in /var/www/wp-content/plugins/recycle-plugin/admin/redux-framework/inc/classes/class-redux-functions-ex.php on line 325

The version tested was Redux 4.1.23.

I am not sure if it is this needs to be fixed in the extension, or if it is a bug in the Redux 4. 

Anyway I just wanted to let you know about the issue.

I have reported the issue at WBC importer extension as well:
https://github.com/Webcreations907/WBC-Importer-extension/issues/92

**Comment by kprovance** [comment]
Unfortunately, this is not our extension.  We are unable to offer support for it.
