### ISSUE TITLE
ReduxTemplates/Api() bug in Gutenberg editor in WP 5.6

### ISSUE THREAD

**Issue by yerooleopard** [reduxframework/redux-framework-4#176]
Hello,

I am theme developer and I am using Redux Framework (v4.1.23) as a plugin for my theme options.
After WordPress update to latest version (5.6) there is a bug displayed in Gutenberg Editor caused by ReduxTemplates/Api(). WordPress expect api_hooks to be an array not string.

```Warning: array_intersect_key(): Argument #1 is not an array in ...\wp-includes\rest-api\class-wp-rest-server.php on line 1402```

Fix this please or allow us to disable ReduxTemplates easily.

PS. Your Redux Framework website and docs are so messed up. Many links doesn't work and I have no idea how and where to buy any extension – I can only see option to buy templates.

**Comment by dovy** [comment]
Resolved. The next release will come today with this fixed. :)
