### ISSUE TITLE
Customizer Issues

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework-4#18]
The following fields (specific field configs) are not firing the redux_change method. Need to resolve.

- [ ] radio
- [ ] text
- [ ] textarea
- [ ] sortable toggle visibility
- [ ] Palette
- [ ] Color RGBA
- [ ] button_set - (Multi select version works, retgular fails)
- [x] select dropdown invisible (css issue)
- [ ] image_select preset
- [ ] spinner
- [ ] Validations don't work
- [ ] Disabling doesn't work in customizer (css)

**Comment by dovy** [comment]
@kprovance Ran out of time. It's an issue with the CSS classes I think in redux.js. Can you take a look? Seems like they changed the HTML classes for the customizer (sigh).

**Comment by kprovance** [comment]
Fields are working and saving again.

Validation/sanitizing is hooked into Redux AJAX save...so it's going to take some work to get that working.  TO DO list.
