### ISSUE TITLE
Fatal Error: Gutenberg (Post edit, Add new)

### ISSUE THREAD

**Issue by wpessential** [reduxframework/redux-framework-4#180]
Hi @dovy,
Today I found an error when I try to update or add the new post in Gutenberg with WordPress 5.6 and Redux 4.1.23. Please check it and let me know if I can help with anything.

![Screenshot_5](https://user-images.githubusercontent.com/24288930/102045707-82793800-3dfb-11eb-8ab6-419894ea22c2.jpg)

**Comment by dovy** [comment]
Update to the newest version of Redux. This has been resolved.   4.1.24 resolves it.  

There was a change in WP core that affected code that worked prior to WordPress 5.6.  :)
