### ISSUE TITLE
Call to undefined finction wp_rand

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework-4#181]
The client is getting an error Call to undefined function wp_rand() in /home/sc2bupa2251/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-args.php:202 

https://secure.helpscout.net/conversation/1362686426/130/

**Comment by mohammedeisa** [comment]
Another report:
https://wordpress.org/support/topic/an-error-of-type-e_error-was-caused-in-line-202/

**Comment by dovy** [comment]
Get me a wp-admin access to one of them and I'll see what I can do.

**Comment by dovy** [comment]
I'm pretty sure this has been resolved. Please reopen if the problem persists.
