### ISSUE TITLE
Error Only variables should be passed by reference in /home/tedcoil/public_html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-functions-ex.php on line 311....

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework-4#182]
Two clients have reported this error:
Only variables should be passed by reference in /wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-functions-ex.php on line 311

**Comment by dovy** [comment]
Yes, already fixed this morning.  ;)

**Comment by mohammedeisa** [comment]
Is the fix for this bug included in the last release?
