### ISSUE TITLE
The post comments form is not being shown when the page attribute is set to Redux contained

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework-4#184]
## Steps to reproduce

- Activate Redux Pro with a default theme
- Make sure that you enabled the discussion for posts in Settings > discussion
- Create a new post and check it in the frontend to see that the comments for exits
- Edit the post and select Redux contained from the page attribute setting
- Visi the post again and see that the comments form is not there

##Expected behavior
The comments form should exist in the post while the Redux contained attribute is selected.

## Errors
No errors

**Comment by dovy** [comment]
The fix has been pushed to the repo and will be part of the 4.1.25 release.

**Comment by mohammedeisa** [comment]
I confirm that this issue has been fixed in 4.1.25. Closing.
