### ISSUE TITLE
button_set display issue on WP v5.6

### ISSUE THREAD

**Issue by STV11C** [reduxframework/redux-framework-4#186]
Hi, it appears the **button_set** on the latest version on WordPress is showing an icon above the label. See screenshot attached.

I noted that the markup of the button_set is different on the latest WP 5.6 vs WP5.5x. e.g.
`class="buttonset ui-buttonset ui-controlgroup ui-controlgroup-horizontal ui-helper-clearfix"` (latest WP version)
vs
`class="buttonset ui-buttonset"` (old WP version)

Anyone else having this issue?

![Capture](https://user-images.githubusercontent.com/5532744/104582461-04d37100-56b4-11eb-9425-dcaa9e5a4c16.PNG)

**Comment by dovy** [comment]
I am as well. WP core changed something internally. If you're willing to try and help find the issue I'd love that. I can't seem to pinpoint it...

**Comment by theme-x** [comment]
At my end, it's showing like the shot below

![Screenshot 2021-01-20 19 11 16](https://user-images.githubusercontent.com/53013260/105179335-6b90d880-5b53-11eb-814e-e8511d92442a.png)
