### ISSUE TITLE
Theme config file is not readed anymore since new version

### ISSUE THREAD

**Issue by helvetica123** [reduxframework/redux-framework-4#192]
I developed a Wordpress theme with redux.It was nice, I was using all functions of redux in the theme.However, since new version, redux doesn't read my custom config file anymore.So, there is no theme panel on my theme.Now, only default options seem.

I couldn't find any article about migrating theme to new redux version.So, how can I converted my theme for new redux?

in my theme plugin there is this line, it had been worked but not works anymore:

include_once( get_template_directory() . '/inc/sample-config.php' );

it named sample-config but its actually customized file.
theme installs redux from Wordpress repo with tgm plugin.

so, what must I do to fix?

need create new config PHP file for new version? if it is yes, is there any converter?

**Comment by helvetica123** [comment]
now, I enabled demo panel under tools>redux, saved data display on pages but demo control panel seems on wp-admin instead of customized panel.

theme reads default values of option from custom config file but custom panel doesn't seem on wp-admin.it display demo panel on wp-admin

**Comment by mohammedeisa** [comment]
We didn't encounter issues similar to yours. Could you please upload your config file and share the download link with me?

**Comment by helvetica123** [comment]
> We didn't encounter issues similar to yours. Could you please upload your config file and share the download link with me?

I hope you will a solution.Here the file:
https://drive.google.com/file/d/1jws-x-W5v2Bt41DI0nLRP7EabpLpmTyW/view

**Comment by helvetica123** [comment]
I disabled the redux plugin and enabled it again and it started works.I don't know the reason but there is no problem now.
