### ISSUE TITLE
Warning: Use of undefined constant defaults - assumed 'defaults'

### ISSUE THREAD

**Issue by mihdan** [reduxframework/redux-framework-4#20]
This will throw an Error in a future version of PHP

> in /home/m/mihdan/wp-digest.ru/public_html/wp-content/plugins/mihdan-yandex-turbo-feed/vendor/redux-framework-4/ReduxCore/inc/classes/class-redux-api.php on line 1222

Version 4.0.1.6

**Comment by kprovance** [comment]
It's a typo.  Will push a fix later today.  Thanks!

**Comment by kprovance** [comment]
Fixed in latest push
