### ISSUE TITLE
Deprecated warnings in the backend

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework-4#203]
# Issue description
I'm getting the following deprecation warnings in the backend:
Deprecated: Required parameter $field follows optional parameter $opt_name in \redux-framework-master\redux-core\inc\classes\class-redux-options-defaults.php on line 89

Deprecated: Required parameter $wp_customize follows optional parameter $args in \redux-framework-master\redux-core\inc\extensions\customizer\class-redux-extension-customizer.php on line 574

Deprecated: Required parameter $wp_customize follows optional parameter $args in \redux-framework-master\redux-core\inc\extensions\customizer\class-redux-extension-customizer.php on line 597

Deprecated: Required parameter $wp_customize follows optional parameter $args in \redux-pro\core\inc\extensions\advanced_customizer\class-redux-extension-advanced-customizer.php on line 361

Deprecated: Required parameter $wp_customize follows optional parameter $args in \redux-pro\core\inc\extensions\advanced_customizer\class-redux-extension-advanced-customizer.php on line 381

Warning: Only the first byte will be assigned to the string offset in E:\wamp\www\redux_training\wp-includes\class.wp-scripts.php on line 492

Deprecated: Required parameter $handle follows optional parameter $register in \redux-framework-master\redux-core\inc\classes\class-redux-cdn.php on line 96

Deprecated: Required parameter $src_cdn follows optional parameter $register in \redux-framework-master\redux-core\inc\classes\class-redux-cdn.php on line 96

Deprecated: Required parameter $deps follows optional parameter $register in \redux-framework-master\redux-core\inc\classes\class-redux-cdn.php on line 96

Deprecated: Required parameter $ver follows optional parameter $register in \redux-framework-master\redux-core\inc\classes\class-redux-cdn.php on line 96

Deprecated: Required parameter $footer_or_media follows optional parameter $register in \redux-framework-master\redux-core\inc\classes\class-redux-cdn.php on line 96

Deprecated: Required parameter $handle follows optional parameter $register in \redux-framework-master\redux-core\inc\classes\class-redux-cdn.php on line 170

Deprecated: Required parameter $src_cdn follows optional parameter $register in \redux-framework-master\redux-core\inc\classes\class-redux-cdn.php on line 170

Deprecated: Required parameter $deps follows optional parameter $register in \redux-framework-master\redux-core\inc\classes\class-redux-cdn.php on line 170

Deprecated: Required parameter $ver follows optional parameter $register in \redux-framework-master\redux-core\inc\classes\class-redux-cdn.php on line 170

Deprecated: Required parameter $footer_or_media follows optional parameter $register in \redux-framework-master\redux-core\inc\classes\class-redux-cdn.php on line 170

Deprecated: Required parameter $parent follows optional parameter $field in \redux-framework-master\redux-core\inc\extensions\options_object\options_object\class-redux-options-object.php on line 31

Deprecated: Required parameter $parent follows optional parameter $field in \redux-framework-master\redux-core\inc\extensions\import_export\import_export\class-redux-import-export.php on line 32

**Comment by kprovance** [comment]
Most of these I fixed in that #203 pull request.  I no longer have access to the Pro library, so there's nothing I can do about that.  As for 'redux_training', I have no idea what that is.  After my time, I assume.

There are also a plethora of other fixes in my pull request, including the deprecated jQuery calls in all the JS, because the day is coming WP will pull the migrate library and people will be hosed.

**Comment by arturgrabo** [comment]
@kprovance when we find time to chat we can also get you access to the Pro library.

**Comment by mohammedeisa** [comment]
@kprovance so, we keep this issue open until the changes you made get merged and test it?

**Comment by mohammedeisa** [comment]
@essamamdani has confirmed that this issue has been fixed.
Closing here.
