### ISSUE TITLE
Switch Field is not working - no reaction on click

### ISSUE THREAD

**Issue by mneitz** [reduxframework/redux-framework-4#205]
## Support Hash
https://support.redux.io/?id=1qjH0RSAVzLlTLcl512MLkK9hhm5Z53jjT3ABPIHWRMXNAmXCvd0e21A2pVucgfk%2F7p0ybujiRTnp9RT6n%2BsGQ%3D%3D

## Steps to reproduce
I Included an Switch field into a metabox of an custom posttype and for whatever reason the switch-button can not be clicked at all... there is no error in the console, and in other plugins it is working :/

- you will find in the left menu the custom posttype "Kongress Warehouse" and you can add a new connector.

## Expected Behavior
I expected that the switch button can be switched on and off

## Actual Behavior
no change if you click the switch button

## Any Error Details (PHP/JavaScript)
JS Console is empty as well as no errors in PHP

**Comment by dovy** [comment]
Please try the code in this repo. We're getting ready for a release that solves this issue. Let us know if it works for you.

**Comment by mneitz** [comment]
Hi Dovy,
Thx for the fast response
I installed the update but it is still NOT clickable :/

- I tried to remove the upload/redux
- I created an additional Tab in the metabox as this is the only difference i can see to the other customs Posttypes ( in my other plugins )

**Comment by mneitz** [comment]
Hi Dovy,
Do you need anything from my side? I am still holding the environment for you for testing!
best regards - Martin

**Comment by mohammedeisa** [comment]
@essamamdani Please check if this issue has been fixed.

**Comment by mneitz** [comment]
I checked it from my side and it is still NOT working

**Comment by mohammedeisa** [comment]
@mneitz Thanks for the update. We will handle this ASAP.

**Comment by essamamdani** [comment]
I double-checked everything on my end and it works well, just as you said. If it doesn't work, please tell me how to reproduce it.

**Comment by mneitz** [comment]
Hi Essa,
If you want, I can grant you access to the installation where it does not
work.
many THX - Martin

Am Sa., 22. Mai 2021 um 15:41 Uhr schrieb Essa Mamdani <
***@***.***>:

**Comment by essamamdani** [comment]
Hi Martin,

Yes. Please send me the installation’s instructions. Thanks

**Comment by mneitz** [comment]
Hi essamamdani,
I prepared an installation for you - where shoud i send you the login information to?

**Comment by kprovance** [comment]
@mneitz - I'll be taking over the debugging support for Redex next week.  In the interim, I have followed this issue, unable to reproduce it, and would like to get it resolved for you and apply the appropriate fix to Redux, if any.  My email is kevin.provance@gmail.com.  Please also let me know which section of your options panel this issue occurs so I can personally examine it.  Thanks!

**Comment by essamamdani** [comment]
> Hi essamamdani,
> I prepared an installation for you - where shoud i send you the login information to?

here is my email Mamdani.info@gmail.com you can provide login details here....

**Comment by kprovance** [comment]
For those watching, the switch isn't responding because the JavaScript for the switch isn't loading.  As far as I can tell, so far, is because the project is embedded in a plugin, and only loads options in a metabox panel.  There doesn't seem to be a global panel, and it's my theory this is why the control JS isn't loading.  I've asked the author to send me a copy of his plugin so I can debug it locally and figure out why Redux won't load control JS when only declared in a metabox panel.  WIll post back when a solution is ready.

**Comment by kprovance** [comment]
We solved this via email.  No update to the Redux core was necessary.  It was a metaboxes issue.

**Comment by mneitz** [comment]
THX to the great Team behind REDUX!
