### ISSUE TITLE
Css compiler error

### ISSUE THREAD

**Issue by webbudesign** [reduxframework/redux-framework-4#206]
Hello, guys hope you well.

I found a problem and this affecting CSS compiler output. I used CSS rules like this `.pfnavmenu li.selected > a`, and it was working before. Now system exporting like this https://jmp.sh/quPmHj2 and this breaks the entire rule.

I am using Version 4.1.24  (Wordpress Release version)

**Comment by webbudesign** [comment]
I found the problem. 
https://github.com/reduxframework/redux-framework-4/blob/7c37c302a097b5095899018a7b14e007e416a8c6/redux-core/inc/fields/link_color/class-redux-link-color.php#L336

You are using esc_attr() but this is removing <> characters. 

https://github.com/reduxframework/redux-framework-4/blob/7c37c302a097b5095899018a7b14e007e416a8c6/redux-core/inc/fields/link_color/class-redux-link-color.php#L309

Also, you are not using esc_attr on output.

**Comment by kprovance** [comment]
Fixed in the latest pull request, 4.1.27
