### ISSUE TITLE
The single radio field value and label are lost

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework-4#207]
# Issue desctiption:
In the smaple options, the single radio field loses its label and value after saving it for the first time,

**Comment by mohammedeisa** [comment]
On Redux 4.1.24 , almost the same issue happens except that, in Redux 4.1.24 the first time you save the field, the option label doesn't get lost.

**Comment by essamamdani** [comment]
I double-checked everything on my end and it works well, just as you said. If it doesn't work, please tell me how to reproduce it.

**Comment by mohammedeisa** [comment]
Here is a video showing the issue:

https://user-images.githubusercontent.com/3139496/119424078-0a496380-bd05-11eb-91c0-84f9e3628f0f.mp4

See at the end of the video that the option text has been lost.

**Comment by essamamdani** [comment]
I am unable to see any sample options...look at the video.

https://user-images.githubusercontent.com/413629/119483533-81ffa880-bd6e-11eb-826a-d96765aa6755.mp4

**Comment by mohammedeisa** [comment]
@essamamdani To see the sample options, you need to activate the dev mode from Tools > Redux framework.

**Comment by kprovance** [comment]
Fixed in the latest pull request, 4.1.27
