### ISSUE TITLE
Remove the donation text from the demo sample options page

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework-4#210]
Remove the following text from the sample options page in Sample options > Documentation

_We still need your support!
It is difficult and time consuming to continue development and support for this free plugin without contributions from users like yourself. If you enjoy using Redux Framework, find it useful, and if it's saved you hours upon hours of development time, please consider donating and helping us hit our fundraising goal. Your donations will help encourage and support the plugin’s continued development and better user support._

**Comment by essamamdani** [comment]
I find donation text in (inc/welcome/welcome.php) this file...if this is the file let me know so I can remove it

**Comment by mohammedeisa** [comment]
I'm also not able to see the donation text mentioned in this issue description. Please remove the donate button.

**Comment by kprovance** [comment]
Done
