### ISSUE TITLE
assets css error in localost net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by mahdinai** [reduxframework/redux-framework-4#214]
Hi, assets css error in localhost :
net::ERR_ABORTED 404 (Not Found)

**Comment by mohammedeisa** [comment]
@mahdinai Closing here as there is no enough information about this bug report.

Please mention the needed steps to reproduce the issue, you may also attach screenshots for further clarification. I will reopen this issue once I get this information from your side.
