### ISSUE TITLE
Conflict with bbPress. private parent forum gets unassigned

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework-4#217]
## Issue description:
When Redux is active, the private parent forum gets unassigned from its children after doing any update to the child.

## Steps to reproduce:
- On a fresh install, activate bbPress, in the toolbar click on Forums, then Add New.
--  You should see something like this: https://imgur.com/a/o6VZZ6F
- Activate Redux, you will not see bbPress menu, deactivate Redux again to continue the following steps.
- Add a title to the new forum and then publish.
- Add New forum, give it a title, set visibility to private, and then publish.
- Add New forum, give it a title, click on parent inside bbPress’s Forum Attributes, you should see both forums you’ve made so far, click the one you’ve made private, and then publish, the forum will get published normally.
- Activate Redux again and update the child forum.
--  The forum is published but the parent is reset to — No parent —
- Click on Redux’s Forum Attributes, you can’t see the private forum and thus can’t select it.
--  This bug also applies when Type is set to Category and when Visibility is set to Hidden.

## Ticket: 
https://wordpress.org/support/topic/redux-and-bbpress-glitchy-forum-parents/

**Comment by kprovance** [comment]
This fix for this is available from this repo.  It'll be available on the wp.org repo for the July update.  Thanks!
