### ISSUE TITLE
Increase the select fields' widths

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework-4#225]
Note: This is a usability issue.

The widths of the select fields are a bit small and they can't show the text in their options.

Screenshot:
![image](https://user-images.githubusercontent.com/3139496/123849245-dde2c180-d918-11eb-8177-aa2410103848.png)

**Comment by kprovance** [comment]
Agreed.  I'll adjust the sample-config.

**Comment by kprovance** [comment]
Fixed.
