### ISSUE TITLE
The spinner with two sliders field doesn't work properly

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework-4#226]
The drop-downs on the left and right of the spinner in the "Slider Example 3 with two sliders" field don't respond every time you change their values.

Steps:
Go to Sample options -> Slider/Spinner
Test the "Slider Example 3 with two sliders" field by changing the left and right drop-downs values and see that they are not responding every time.

![image](https://user-images.githubusercontent.com/3139496/123849835-914bb600-d919-11eb-834f-5a86d7ccb6ed.png)

**Comment by kprovance** [comment]
It's a 'step' issue.  Ideally, the selected value not falling on the step should j ump to the nearest step value, but it does not.  That's a select2 issue.  I'll look into upgrading that library and see if it changes anything.  If not, I'm sure I can write my own.  It'll take time and extra testing, so I'll save this for the July released.  Also, moving issue to the new repo.
