### ISSUE TITLE
Warning: Undefined property: Redux_Multi_Text::$show_empty

### ISSUE THREAD

**Issue by mohammedeisa** [reduxframework/redux-framework-4#227]
The following error exists in Advanced features > Field validation > Multi Text Option - Color Validated

Warning: Undefined property: Redux_Multi_Text::$show_empty in E:\wamp\www\redux_training\wp-content\plugins\redux-framework-release-test\redux-core\inc\fields\multi_text\class-redux-multi-text.php on line 64

**Comment by kprovance** [comment]
Fixed
