### ISSUE TITLE
Ad Remover Extension - Still getting charged for it

### ISSUE THREAD

**Issue by STV11C** [reduxframework/redux-framework-4#228]
Hi Dovy and Kevin

Long time no speak and I hope all is well.

I wasn't sure the best place to post this, but I've been charged again for the Ad Remover extension.

This is the second time I've been charged again after cancelling the auto-renewal, and I still haven't received the refund from the initial time it happened.

Can you please ensure my Credit Card is removed from what ever system is charging me, and please provide a refund.

Regards

<img width="388" alt="Capture" src="https://user-images.githubusercontent.com/5532744/132145499-7bc8375a-e2e2-40b6-bcdf-75116a60473b.PNG">

**Comment by kprovance** [comment]
Dovy no longer owns Redux and I no longer have admin access.  I sent this to the new owner so he can process this.  I'll let you know when I hear back.  It may be later in the week due to the holiday.

**Comment by STV11C** [comment]
Thanks for actioning this Kevin. I'm going to contact my bank now to try and stop the transaction too. Hope all is well with you.

**Comment by kprovance** [comment]
I'm being told they cannot find the order.  Did you use Stripe or Paypal?  And the email address you used?  If you're not comfortable posting this, you can email it to me.  kevin.provance@gmail.com

**Comment by STV11C** [comment]
I'm pretty sure it was via the redux website with my Credit Card. I will email you my email I think I would have used. Note that I also had to cancel my credit card and issue a new one just to ensure it doesn't get charged again. My bank may be able to get the money back for me, but would be easier if it can be resolved otherwise. I wonder if Dovy would know?

**Comment by arturgrabo** [comment]
Hi @STV11C - we have checked our billing/subscription system and PayPal account and we don't have record of those transactions in either place. We've looked based on date, amount, name, last 4 digits of credit card, etc. and have no record of it. I recommend you contact your bank to have the charge reversed.

**Comment by STV11C** [comment]
Hi @arturgrabo. That is very strange considering my bank description. I would assume Dovy had/has an account that is drawing these funds. As I mentioned previously this is the second year I've been charged for this add-on after I cancelled the auto renewal via the redux.io website.

Ok I will get my bank to recover the funds.

**Comment by arturgrabo** [comment]
It does seem odd, but I really don't know. I checked with Dovy and he is unaware of any other account.

**Comment by arturgrabo** [comment]
@STV11C sorry I found it. For some reason I thought you wrote you had paid with PayPal, which you hadn't, so I only looked there. I did find the payment in Stripe and just refunded it.

**Comment by STV11C** [comment]
@arturgrabo thanks and glad you found it. I'll let you know when the money reaches my account. Has the auto-renew been cancelled from Stipe's end (or whatever is triggering the auto-renew) so I don't get charged again?

**Comment by arturgrabo** [comment]
Yes I cancelled the Stripe auto-renew

**Comment by STV11C** [comment]
Ok great thanks. I wonder if the refund will come through as I cancelled my Credit Card. If not, it may be easier it is refunded to my PayPal account. I will let you know if a few days if it's come through.
