### ISSUE TITLE
WP 6 PHP Notice

### ISSUE THREAD

**Issue by andrejarh** [reduxframework/redux-framework-4#234]
I just tested WP 6 and a PHP notice appears:

Notice: Function add_menu_page was called incorrectly. The seventh parameter passed to add_menu_page() should be numeric representing menu position. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 6.0.0.)

It is reffering to args['page_priority'] in public options_page function located at /inc/classes/class-redux-page-render.php

```
				$this->page = call_user_func(
					'add_menu_page',
					$core->args['page_title'],
					$core->args['menu_title'],
					$core->args['page_permissions'],
					$core->args['page_slug'],
					array(
						$this,
						'generate_panel',
					),
					$core->args['menu_icon'],
					$core->args['page_priority']
				);
```

**Comment by kprovance** [comment]
I'm not seeing this in my notices or error logs. Please describe the steps you are taking.

**Comment by andrejarh** [comment]
If the config file has this line:
'page_priority'             => null,
like in official sample config:  https://github.com/reduxframework/redux-framework-4/blob/master/sample/sample-config.php
then PHP notice appears. 

Setting this to any number resolves the issue.

**Comment by kprovance** [comment]
This version of Redux 4 in this repo is no longer supported. Please use this one: https://github.com/reduxframework/redux-framework

If this issue persists after that, create a ticket there. Please be mindful of the posting instructions, as we require specific information for support. Thanks.

**Comment by andrejarh** [comment]
i tested it on latest release 4.3.14
[4.3.14](https://github.com/reduxframework/redux-framework/releases/tag/4.3.14)

**Comment by kprovance** [comment]
Please post in the proper repo, and please follow the posting instructions. Specific information in required.
