### ISSUE TITLE
Google Fonts not loading on Front-end

### ISSUE THREAD

**Issue by STV11C** [reduxframework/redux-framework-4#25]
## Support Hash
https://support.redux.io/?id=7X91%2FP605ikM1%2Bc0E5l6iLSR%2FLZqcW%2B%2Bbu2YIfVOGak8%2FzaOUycs7RhrZGSSUZewtmNGhEfPh%2FnYhV9DGAQ%2BZA%3D%3D

## Steps to reproduce
Use the Typography field with a Google Font. Within WP Admin it all works as expected. On the front-end however the Google Font does not load. Looking at the Browser Network Tab within the Console, the Google scripts are not there. 
Note: They load as expected in Redux v3.

## Expected Behavior
Google Font Scripts to load on front-end.

## Actual Behavior
No scripts loading.

## Any Error Details (PHP/JavaScript)
No errors.

**Comment by dovy** [comment]
Issue is in ~/inc/classes/class-redux-output.php. I believe it's loading before the fields are registered. Line 161.

**Comment by dovy** [comment]
Found the issue: https://github.com/reduxframework/redux-framework-4/blob/master/ReduxCore/inc/classes/class-redux-field.php#L160-L164

Now to fix the if statement. Should be done here shortly...

**Comment by STV11C** [comment]
Ok great cheers... although I am am getting used to Times New Roman... kiddin!

**Comment by dovy** [comment]
Just pushed a fix using your theme's code. Give it a try from this repo. The issue should be resolved. Please confirm.

**Comment by STV11C** [comment]
Thanks Dovy, all fixed! :)

**Comment by dovy** [comment]
Superb. Best of luck!
