### ISSUE TITLE
Setting a multi-select's Ajax_save to false is still saving via ajax.

### ISSUE THREAD

**Issue by rgostic** [reduxframework/redux-framework-4#28]
## Support Hash
https://support.redux.io/?id=z91qnq4ZJfsaZn6IWypP6u1zBMnpvmnX8el4HC4F0KvIajmclqMaD1arb3N9CzFNXNgbi9m2K68z%2FAYKwMuZjA%3D%3D

## Steps to reproduce
Create a multi-select and set ajax_save => false. Add or remove items and save.
## Expected Behavior
I expected the page to reload.

## Actual Behavior
The page did not reload.

**Comment by dovy** [comment]
Umm, can you give more details please?
