### ISSUE TITLE
Setting class of multi text field sets class attribute of only the first textbox.

### ISSUE THREAD

**Issue by rgostic** [reduxframework/redux-framework-4#29]
## Support Hash
https://support.redux.io/?id=z91qnq4ZJfsaZn6IWypP6u1zBMnpvmnX8el4HC4F0KvIajmclqMaD1arb3N9CzFNXNgbi9m2K68z%2FAYKwMuZjA%3D%3D

## Steps to reproduce
Create a multi text field and set it's class.

## Expected Behavior
Every textbox to have the class applied.

## Actual Behavior
Only the first textbox had the class applied.

**Comment by dovy** [comment]
Good call. I'll take a look. Shouldn't take much to fix.

**Comment by dovy** [comment]
Actually, wouldn't it be better to just apply the class to the UL instead so regardless of what's added, the class is present? Thoughts?

**Comment by rgostic** [comment]
I agree. Also parent element gives more control with > selector.

Sent from my iPhone

On Apr 5, 2019, at 10:12 AM, Dovy Paukstys <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, wouldn't it be better to just apply the class to the UL instead so regardless of what's added, the class is present? Thoughts?
