### ISSUE TITLE
Typo in class Redux_Core property.

### ISSUE THREAD

**Issue by adrix71** [reduxframework/redux-framework-4#32]
These three properties 

![P](https://user-images.githubusercontent.com/14064365/57251536-5ce65300-704a-11e9-93c1-a162b09710e9.PNG)

are incorrectly declared and many IDEs (eg phpStorm) complain of inconsistencies such as the lack of the __toString() method in the `\project.`

![Cattura](https://user-images.githubusercontent.com/14064365/57251601-80a99900-704a-11e9-8321-e44609b4a6f7.PNG)

If there is no valid reason to declare the type @var as a project (I don't know what reason it could be) I suggest to modify the declaration to reflect the type of data that they must contain so as not to confuse the ide that are already stupid on their behalf ;)

**Comment by dovy** [comment]
I'm actually in PHPStorm as well with the WordPress standards and using phpcs and I see no such standards. Probably it's the standard you've selected. I used to hate the WP standard for this reason, but I'm trying to comply.  :-/

**Comment by dovy** [comment]
Feel free to hop on slack and we can hash it out.  ;)

**Comment by adrix71** [comment]
Tomorrow I will gladly come on slack. I am interested in this thing about the WP standard even though I was sure I configured everything correctly but I am certainly wrong.

**Comment by dovy** [comment]
And maybe I am as well. We'll see.  ;)

**Comment by adrix71** [comment]
Let's hope
