### ISSUE TITLE
Unable to use Redux Builder

### ISSUE THREAD

**Issue by DaltonChakma** [reduxframework/redux-framework-4#34]
Unable to access redux builder. Please fix this issue.

**Comment by 1871vinayak** [comment]
@dovy 
Unable to access redux builder.
Till when it'll get sorted?
Please help!!

**Comment by dovy** [comment]
Try this as a start. ;). https://build.redux.io/alpha/dist/index.html

**Comment by kprovance** [comment]
Redux Builder will soon be offered as part of the Redux Pro offering.  Closing
