### ISSUE TITLE
The metabox extension does not correctly display the indicator to open / close the metabox using Gutenberg.

### ISSUE THREAD

**Issue by adrix71** [reduxframework/redux-framework-4#35]
The metabox extension does not correctly display the indicator to open / close the metabox using Gutenberg or even the icons in the metabox.

This is the screen

![Cattura](https://user-images.githubusercontent.com/14064365/57555353-56224d80-7374-11e9-9750-4bdbe3a2b2fa.PNG)

From JavaScript we understand that a class must be removed and an element added but the `.toggle-indicator` class does not seem to exist when redux is active. If the plugin is not active, it exists.

With plugin
![Cattura](https://user-images.githubusercontent.com/14064365/57555566-f11b2780-7374-11e9-9680-1d67a2ad2455.PNG)

Without plugin
![Cattura](https://user-images.githubusercontent.com/14064365/57555621-19a32180-7375-11e9-81bd-a7cd49a2c275.PNG)

I tried to disable the redux plugin and it works correctly. Can you fix it?

Please note that commenting the line

```php
$( '.postbox .toggle-indicator' ).removeClass( 'toggle-indicator' ).addClass( 'el' );
```
in the redux-extension-metaboxes.js file the problem disappears and the buttons are displayed correctly. 

![Cattura](https://user-images.githubusercontent.com/14064365/57556651-ef9f2e80-7377-11e9-89dc-13d1e8f54572.PNG)

However, the icons are not displayed.

**EDIT:** The icons are break from the class `.block-editor-page` defined in css style. Comment this and now work fine.

![Cattura](https://user-images.githubusercontent.com/14064365/57570367-4b61ca00-7401-11e9-9c36-dc47d085927e.PNG)

**Comment by kprovance** [comment]
Metabox lite has been removed.  Issue moved to Pro board for eval.
