### ISSUE TITLE
Redux_Typography not properly set

### ISSUE THREAD

**Issue by papaexpert** [reduxframework/redux-framework-4#36]
to avoid [13-May-2019 18:12:12 UTC] PHP Fatal error:  Uncaught Error: Class 'Redux_Typography' not found in /home3/wp-content/plugins/redux-framework/ReduxCore/inc/classes/class-redux-output.php:164

goto:

ReduxCore/inc/fields/typography/class-redux-typography.php

copy that file to:

ReduxCore/inc/classes/class-redux-typography.php

**Comment by dovy** [comment]
Can you give me details for this?

**Comment by dovy** [comment]
Closed for inactivity. If these problems persist, please let me know.
