### ISSUE TITLE
Developer Mode  Enabled with message "This has been automatically enabled because you are working in a localhost environment"

### ISSUE THREAD

**Issue by kresimir71** [reduxframework/redux-framework-4#37]
## Support Hash

https://support.redux.io/?id=eyj63%2FOpTVSxHBSpkI%2B%2FFqV43Bk%2BjeUkd3IuEZlQ7n%2BrqiO8syNXW10a33PUj7MiDbxBk0VwaAicbIj0bsskWg%3D%3D
## Steps to reproduce

The website is served on 127.0.0.1 on some port and via haproxy connected to a public IP. It is thus not local installation, but on a VPS. However, the plugin thinks it is local installation.
## Expected Behavior

No local installation detected.
## Actual Behavior

Local installation detected.

**Comment by dovy** [comment]
Oooo. That's a difficult one to detect. Hmm.

Not sure what to do to remove the notice without sending out a patch to enable for all others.

**Comment by carmoreira** [comment]
I personally think the developer mode should just rely on settings and not be enabled automatically in these cases, but I understand that for backwards compatibility it's not such a great idea to change this behaviour....

**Comment by dovy** [comment]
Slack me later.

**Comment by dovy** [comment]
Forced local dev_mode has been removed. Only gets shown now when dev_mode => True and WP_DEBUG => true.
