### ISSUE TITLE
Porting typography field from Redux 3.x.x. in Redux 4. Help please.

### ISSUE THREAD

**Issue by adrix71** [reduxframework/redux-framework-4#38]
Would you please help me bring the redux 3 typography field to use with version 4 ??

This is the screen and I don't understand why it is displayed this way.

![Cattura](https://user-images.githubusercontent.com/14064365/58108869-e1a9a300-7bec-11e9-86da-e897f131f641.PNG)

Thank you

**Comment by dovy** [comment]
Are you sure you're loading Redux properly? I don't seem to have this issue.

Try deferring the loading of your code until plugins_loaded or init, but load Redux much earlier.  ;)

**Comment by adrix71** [comment]
Actually I'm loading the field plugin of version 3 of redux directly from the fields folder (I replaced the directory).

**Comment by dovy** [comment]
That would be why. The fields have changed a lot in Redux 4 with a redux_field class and inheritance. You'll need to add that in.

What broke that made you want to use the old code?

**Comment by adrix71** [comment]
You already know the problem https://github.com/reduxframework/redux-framework-4/issues/30 this bug.

I can't stand that yellow bar at the top and I don't want to turn off the `save_warn` option. I discovered that the problem is in `font-family` (class-redux-typography.php) and in particular the select that create the drop down (line 302) and is due to some javascript point of the typography field but after 10 days I still didn't understand the reason so along with this instruction (file: redux.js, line 2022)

```php
$( '.redux-save-warn' ).css( 'left', $width + 'px' );
```

add a `display: block` that I can't find anywhere. You can see it on the screen below.

![Cattura](https://user-images.githubusercontent.com/14064365/58121729-5fc77300-7c08-11e9-8e21-86f16674944f.PNG)

Ultimately since I am one who when I can't do something pisses me off very easily it's better that I do a rolback waiting to calm down.

**Comment by dovy** [comment]
Serious? I thought I solved that. Didn't I? I'll get back to it and verify.

**Comment by adrix71** [comment]
That problem has never been solved.  You have made it so that once you save the options the message disappears but if you reload the page for any reason it comes back out.

**Comment by dovy** [comment]
Can I suggest, just to make sure it's not a priority issue (hooks):

1. Load redux 4 via plugin (not embed)
2. Delay your plugin/theme code to plugins_loaded or init.

Just trying to isolate some concerns here.

**Comment by adrix71** [comment]
redux4 Is loading via plugin and not embed and not have other plugin installed. This problem concerning redux4.

**Comment by dovy** [comment]
Big shoutout to @kprovance for fixing this. Give it a try, new version in the repo.

**Comment by adrix71** [comment]
Yes work. Now please read and apply this fix (https://github.com/reduxframework/redux-framework-4/issues/33) for Reset Section and Reset All.

And ... thanks dovy, thanks kevin.
