### ISSUE TITLE
Select Field not Saving

### ISSUE THREAD

**Issue by danielbarenkamp** [reduxframework/redux-framework-4#44]
The select field is not saving. I recorded a video here: https://we.tl/t-C3lDcn6MQd

In my error log:
 [05-Jun-2019 07:42:39 UTC] PHP Notice:  Undefined index: opt_name in /XXX/wp-content/plugins/redux-dev-master/ReduxCore/inc/classes/class-redux-class.php on line 50

Its a simple select field:
```
                array(
                    'id'       => $cron.'sourcePostTypes',
                    'type'     => 'select',
                    'title'    => __( 'Source Post types', 'wordpress-multisite-sync' ),
                    'subtitle' => __( 'What post types do you want to sync? Attachments not working today!', 'wordpress-multisite-sync' ),
                    'data' => 'post_types',
                    'multi' => true,
                ),
```

**Comment by dovy** [comment]
So odd! I'll take a look. I'm sure I know the solution.

**Comment by dovy** [comment]
Cannot reproduce. I think it may be resolved. Please post back if you try the new code and still have the same error.
