### ISSUE TITLE
Import/Export demo

### ISSUE THREAD

**Issue by lththeme** [reduxframework/redux-framework-4#45]
Hi,

We are a team of developers who are beginning to publish our theme on Themeforest. We are facing an issue in presenting the demo of our theme and wanted to seek your help.

Whenever we try to export our theme demo content and import it somewhere else, the pictures don’t go in their correct position as before. 
The image’s IDs in imported demo is not the same as ID’s in the exported demo. For example, Logo’s ID was 6 in exported demo but it was appeared in imported demo with number 21.
We use Wpbakery for page building and Redux Framework for theme option.

Is there a plugin or tool we can use to fix our problem or should we follow certain criteria?

**Comment by dovy** [comment]
Hmm, that's a good point. The order isn't maintained. I am sorry for the delay in response. The short answer is I don't think there's a quick answer. But I'm going to leave this open as an issue we need to resolve.

**Comment by kprovance** [comment]
Are you speaking of option set in the Redux panel, or page content designed in WPBakery?  Redux doesn't export or import page content.  I'm sure sure what system you may be using to import/export demo content, but it's probably not Redux itself.  If it's a tool that uses Redux, then you'd need to contact the author of that code.
