### ISSUE TITLE
Repeater Extension Error in WP Admin

### ISSUE THREAD

**Issue by STV11C** [reduxframework/redux-framework-4#46]
## Support Hash
https://support.redux.io/?id=7X91%2FP605ikM1%2Bc0E5l6iLSR%2FLZqcW%2B%2Bbu2YIfVOGak8%2FzaOUycs7RhrZGSSUZewtmNGhEfPh%2FnYhV9DGAQ%2BZA%3D%3D

## Steps to reproduce
Install the Repeater Extension (v1.0.4) with the latest version of WP5 and Redux 4 Beta and view it in the Admin.

## Expected Behavior
To work as expected.

## Actual Behavior
UI appears broken. Cannot add repeaters. Console error.

## Any Error Details (PHP/JavaScript)
Uncaught ReferenceError: redux is not defined at field_repeater.min.js?ver=1560767877:1

**Comment by dovy** [comment]
I'll take a look.

**Comment by dovy** [comment]
You're correct and it's an issue we have to fix with all the extensions. We rebuilt the redux extension class and have to finish resolving backwards compatibility. Once we do, I'll let you know.

**Comment by dovy** [comment]
@STV11C can you give this a try again? I just pushed some code that _SHOULD_ fix the issues with older extensions. I would appreciate you giving it a try.

**Comment by STV11C** [comment]
@dovy Seems to all work well thank you! There is just 1 console error on a Reset All, but may be from something else. Screen attached.
<img width="925" alt="Capture" src="https://user-images.githubusercontent.com/5532744/62526009-bfcecc80-b87b-11e9-86ce-c51116a5a32a.PNG">

**Comment by STV11C** [comment]
Actually... the Metabox Lite setting don't appear anymore

**Comment by dovy** [comment]
K, I’ll take a look.

**Comment by kprovance** [comment]
As this issue was resolve and Metabox Lite was removed, I'm closing this issue.  Thanks.
