### ISSUE TITLE
color_rgba field issue

### ISSUE THREAD

**Issue by STV11C** [reduxframework/redux-framework-4#48]
**## Support Hash**
https://support.redux.io/?id=7X91%2FP605ikM1%2Bc0E5l6iLSR%2FLZqcW%2B%2Bbu2YIfVOGak8%2FzaOUycs7RhrZGSSUZewtmNGhEfPh%2FnYhV9DGAQ%2BZA%3D%3D

**## Steps to reproduce**
Add a simpe color_rgba field. e.g.
```
array(
  'id'        => 'opt-color-rgba',
  'type'      => 'color_rgba',
  'title'     => 'RGBA Color Picker',
  'default'   => array(
    'color'     => '#fdfdfd',
    'alpha'     => 1
  ),      
),
```

**## Expected Behavior**
To see the alpha channel

**## Actual Behavior**
Did not see the alpha channel, just normal color picker.

**## Any Error Details (PHP/JavaScript)**
No console errors.

**Comment by dovy** [comment]
Resolved. Please pull. Small typo in the JS.  ;)

**Comment by STV11C** [comment]
Hey Dovy. Tested and working as expected! Cheers!
