### ISSUE TITLE
Redux 4 Global Argument Error

### ISSUE THREAD

**Issue by themecatinfo** [reduxframework/redux-framework-4#51]
Hi team redux,

I have found an error on the global argument database ( theme_mods, theme_mods_expanded ).
When I add the database like theme_mods or theme_mods_expended, I have found an error on saving of redux options and error is Ajax: warning.
And here is the errors list by actions.

PHP Warning: Illegal offset type in ReduxCore\framework.php on line 661.
PHP Stack trace:
PHP 1. {main}() wp-admin\admin-ajax.php:0
PHP 2. do_action() wp-admin\admin-ajax.php:173
PHP 3. WP_Hook->do_action() wp-includes\plugin.php:465
PHP 4. WP_Hook->apply_filters() wp-includes\class-wp-hook.php:310
PHP 5. Redux_AJAX_Save->save() wp-includes\class-wp-hook.php:286
PHP 6. Redux_Options->validate_options() ReduxCore\inc\classes\class-redux-ajax-save.php:80
PHP 7. ReduxFramework->set() ReduxCore\inc\classes\class-redux-options.php:923

This error was so hard to find out for me. Because I thought that error is in my PHP code. So, I sorted my PHP code so many times.

And the redux version is **4.0.1.9**.

Regard
Themecat_Info

**Comment by dovy** [comment]
Ahhh, good to know you're using Redux 4. Can you send a support URL, please?

This may have not been tested in the new version of Redux.  ;)

**Comment by themecatinfo** [comment]
> Ahhh, good to know you're using Redux 4. Can you send a support URL, please?
> 
> This may have not been tested in the new version of Redux. ;)

Sorry, @dovy this time my project is only available on localhost.

**Comment by dovy** [comment]
https://docs.redux.io/guides/basics/generating-a-support-hash.html

;)

**Comment by themecatinfo** [comment]
> https://docs.redux.io/guides/basics/generating-a-support-hash.html
> 
> ;)

Ooh sorry :D

here is the hash link

https://support.redux.io/?id=NiqaoHVxxaZ4pmz%2BuXK7S75b5YrDBCksMAz7zIfDl76ofu0Zw3Yca5IpxW341WM4DjiJDyWvPANTMbUzyljToQ%3D%3D

**Comment by dovy** [comment]
Ok, just pushed a fix. Give a test, let me know if you have issues. Good find!

**Comment by themecatinfo** [comment]
> Ok, just pushed a fix. Give a test, let me know if you have issues. Good find!

Good fixed, It's working.
