### ISSUE TITLE
Error In Section Field Type

### ISSUE THREAD

**Issue by themecatinfo** [reduxframework/redux-framework-4#52]
Hi,
I have found an error in the section field type. When I add the info field type in the section and set the indent equal to true, then indent not work on the info field type. Also, section dependency does not work in the inner of this section, field type info.

And the redux version is **4.0.1.9**

Regard
Themecat_Info

**Comment by dovy** [comment]
It's probably because I hadn't documented it properly. It was `sectionIndent` as the key, but I've added a shim and renamed it to `indent` and updated the new docs https://docs.redux.io/core-fields/info.html#arguments.

Pull the newest code from this repo, as it should fix the issue.  :)

**Comment by themecatinfo** [comment]
Hi @dovy,
Now working good but I'm a little bit confused about the section working with info field.
here is my PHP code [https://codeshare.io/ad9O1y](url). After the info field type, the section table divides into 2 tables. One before the info field and 2nd after the info field and section show/hide dependency do not work. Even this, indent does not work on the 2nd table.
