### ISSUE TITLE
Import/Export only works with WordPress Debug on

### ISSUE THREAD

**Issue by STV11C** [reduxframework/redux-framework-4#59]
## Support Hash
https://support.redux.io/?id=bMeP6H0VaCnKmyQVsXvpFjGk9FuB1GgHpwh6dyc2AHW1aHnh0Wx1msNKrTIKiFjTXaG7Ctu3ksjoRQ3i8PCMSQ%3D%3D

## Steps to reproduce
Try to use Import/Export with Debug Off.

## Expected Behavior
Import/Export buttons should work as expected.

## Actual Behavior
Nothing happens when you click buttons.

## Any Error Details (PHP/JavaScript)
No.

**Comment by voldemortensen** [comment]
@STV11C I can't reproduce this with a fresh install and a minimal config. Can you provide more information on what kind of fields you have setup?

**Comment by STV11C** [comment]
@voldemortensen I loaded up the bare bones config and having same problem. To clarify, try with the Redux config `'dev_mode' => false` OR the WordPress config `define('WP_DEBUG', false);`
The only thing that seems to work when debug is false is the 'Download Data File' button.

**Comment by dovy** [comment]
Found the issue, fixed and pushed.
