### ISSUE TITLE
Woocommerce endless spinning on checkout

### ISSUE THREAD

**Issue by Qamdad** [reduxframework/redux-framework-4#6]
I'm using Bemobile theme which depends on redux framework. If I activate Redux Framework I face issue with checkout page it spinning and not load. If I deactivate Redux Framework plugin the checkout will work without any issue but BeMobile thems will not work. Any Idea please.

Thanks in advance

**Comment by kprovance** [comment]
1) This is the Redux 4 beta, not the current buikl
2) We do not support end users of themes that use our framework.  You will need to contact the theme author for support.

Good luck.
