### ISSUE TITLE
'Required' config in Repeater Extension doesn't work

### ISSUE THREAD

**Issue by STV11C** [reduxframework/redux-framework-4#62]
## Support Hash
https://support.redux.io/?id=7X91%2FP605ikM1%2Bc0E5l6iLSR%2FLZqcW%2B%2Bbu2YIfVOGak8%2FzaOUycs7RhrZGSSUZewtmNGhEfPh%2FnYhV9DGAQ%2BZA%3D%3D

## Steps to reproduce
Add a simple 'button_set', and then another basic field with 'required' config for a selection of the button_set.

## Expected Behavior
Toggle visibility.

## Actual Behavior
Does nothing.

## Any Error Details (PHP/JavaScript)
No

**Comment by kprovance** [comment]
This will be addressed in Redux Pro.
