### ISSUE TITLE
JS and CSS files are not loaded

### ISSUE THREAD

**Issue by yapechurin** [reduxframework/redux-framework-4#63]
Hi. Script and style files are not included on all pages of the framework. In the console, all the paths indicated are incorrect. Errors are visible in the screenshot.

The same error in the Tool -> Redux framework. I can not draw up according to your application requirements.

Similar problem here: [Link](https://github.com/reduxframework/redux-framework-4/issues/14)

You have already fix it, but the error has appeared again.

![error](https://user-images.githubusercontent.com/16340225/64204147-d0378e80-ce9d-11e9-9940-79afee32b401.png)

Tested on a clean wordpress. Version of framework at 01.09

**Comment by dovy** [comment]
Using Redux 4 or 3? Please also submit a support url.

**Comment by yapechurin** [comment]
version 4.0.2. The link cannot be generated; the functional does not work. See screenshot
![error2](https://user-images.githubusercontent.com/16340225/64205402-8bf9bd80-cea0-11e9-94e9-9863f157710c.png)

**Comment by rafaelfndev** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/7171869/66389496-e524a780-e99e-11e9-9a6a-6083775c443f.png)

Did you change your default WordPress URL? It looks like you are using the absolute path `/home/.../public_html/` along with the URL. Apparently your URL structure doesn't look right, but I may be mistaken.

**Comment by dovy** [comment]
Good eye @rafaelfndev! Update your site url @yapechurin and things may work better.

**Comment by dragon07** [comment]
Hi I also had the same problem using version 4.3.1 "**Failed to load resource: the server responded with a status of 404 (Not Found**)"

![issual](https://user-images.githubusercontent.com/16411781/136157773-65519224-7aea-4890-a598-c9bc835aeaae.jpg)

**This is the code I integrated:**

![issua2](https://user-images.githubusercontent.com/16411781/136157905-8010c04e-249d-417a-aad7-ac0d4d71434f.jpg)

Please help! Thanks

**Comment by kprovance** [comment]
Try using the plugin and see if the problem is resolved.

**Comment by rapcrown** [comment]
I'm getting the same error, could it be due to the version?

**Comment by armin0chehr** [comment]
> Try using the plugin and see if the problem is resolved.

Yah it is solved after installing plugin but
I want to use it in theme mode

**Comment by mmdQanbari** [comment]
hi
you should change your theme name, This problem occurs when the name of the original project file and the theme name are the same.
