### ISSUE TITLE
Reset options issue when using a 'Sorter' with a 'Repeater' Extension

### ISSUE THREAD

**Issue by STV11C** [reduxframework/redux-framework-4#64]
## Support Hash
https://support.redux.io/?id=7X91%2FP605ikM1%2Bc0E5l6iLSR%2FLZqcW%2B%2Bbu2YIfVOGak8%2FzaOUycs7RhrZGSSUZewtmNGhEfPh%2FnYhV9DGAQ%2BZA%3D%3D

## Steps to reproduce
Using a 'Sorter' with a 'Repeater' Extension - When resetting options to default, the Repeater (which is also an array) is not set until a Save.

## Expected Behavior
When resetting options using 'Sorter' the 'Repeater' default option should also be set. 

## Actual Behavior
'Repeater' is not set and get the undefined index error below. Note I am using a foreach for the 'Repeater' in my template, so the error relates to the loop.

## Any Error Details (PHP/JavaScript)
Notice: Undefined index: opt-XXX in /var/www/html/wp-content/themes/XXX/XXX.php on line 16 Warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/themes/XXX/XXX.php on line 16

**Comment by kprovance** [comment]
I am unable to reproduce this, thus far.   Is that obfuscated error log part of Redux or your theme?  If it is your code erroring out, you may need to do isset or is_array checked on the global variable.

**Comment by STV11C** [comment]
Hi Kevin, great to hear from you and thanks for the response. As this
ticket was a while ago I can't actually remember what I was trying to
achieve, so feel free to close it for now. Regards, Stephan
