### ISSUE TITLE
fields: output CSS variables

### ISSUE THREAD

**Issue by andrejarh** [reduxframework/redux-framework-4#65]
Hi,
First of all this isn't a bug report, but just an idea, you might consider incorporating into the framework (if you think it makes sense).

Curently Redux fields have option to either output css directly or to use a compiler (or both). 
This is something which is in Redux for a long time and it works just fine. 

But modern front end development has gone a long way. Now [css variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) are used everywhere. It is already possible to create css variables with compiler (this is how we implement them). But it would be great if there would be an option to create them directly without compiler 

I see two possible options, one is to extend the 'output' field, or second, to create a new option (ie  'variable_output')

So here are both examples how it could be used on a color field:

![image](https://user-images.githubusercontent.com/10053621/64528939-fa5bd700-d309-11e9-8957-1bc704a85c1f.png)

so if the output field would be used:
`array(
    'id'       => 'dark_color',
    'type'     => 'color',
    'output'      => array( 
        'background-color' => '.footer',
        'css_variable' => '--dark-color',
    ),
),`

or if this was separated from the output field:

`array(
    'id'       => 'dark_color',
    'type'     => 'color',
    'output'      => array( 
        'background-color' => '.footer',
    ),
    'variable_output' =>  '--dark-color',
),`

Let me know what you think.

**Comment by dovy** [comment]
I love this idea and definitely want to incorporate something like this. I do, however, want to make some suggestions and get your suggestions.

First, how would the output officially look in your mind? I want to see what your thoughts are. In my eyes. Because say typography, or border can have multiple "outputs".

Wouldn't it be easier, and just as efficient, to just set a variable, have the standard values passed, and then react accordingly?

What would really help is some examples of the field declaration and the output for a variety of fields. Please keep thinking on this. I've wanted to add this feature for years.  ;)

**Comment by andrejarh** [comment]
I guess it makes sense to simplify the CSS variables output. 
Variables could even be autogenerated by using field ID and appended the "suboptions". 

So this (3rd) suggestion would actually be the simplest option to generate the variables.
Here is a typography field example, with some of the fields disabled, for easier reading:


![image](https://user-images.githubusercontent.com/10053621/64602065-613ac800-d3be-11e9-9b04-3687e1298ca4.png)

**Comment by andrejarh** [comment]
To follow the redux syntax in the upper comment css_variables, should actually be css-variables.
For the border field, here is the full example with final css output:

![image](https://user-images.githubusercontent.com/10053621/64603819-3ef67980-d3c1-11e9-9a10-4e447e0b488f.png)

**Comment by dovy** [comment]
Now this I absolutely love. Simple and complete. The only alteration I would add is a global variable to customize the prefix. $, -, @ could all be valid prefixes. 

What do you think?

**Comment by dovy** [comment]
And should these variables be added to CSS output on the page or just an array of values sent to the compiler hook?

**Comment by andrejarh** [comment]
I think they should be just concencated together (from all fields where css-variables is set to true), then added to the css output - within the :root { } to make them "global" (as the borders example above).

Also an obvious but important note: 
i think default setting for css-variables should be set to false, to prevent any unneccecery css.

**Comment by dovy** [comment]
Merry Christmas.  ;) . Download the newest version and give it a try.

`output_variables => true` can be set at field or section level.
`output_variables_prefix => true` can be set at the global args, field or section level.

I'd appreciate you testing this a bit since I added the feature to function for fields that don't have dynamic output. IE, fields like the slider or spinner can now be stuffed in variables.  ;)

**Comment by dovy** [comment]
We should probably set a number of fields that are not permitted. Raw, textarea, ace_editor. Give me your thoughts, please.

**Comment by dovy** [comment]
Decided to follow the standard we set before. A field class must have a public `output_variables` method defined for it to function. I've added this method to the following field types. If you can see a use case for any other, please do let me know.

- background
- border
- color
- color_gradient
- color_rgba
- dimensions
- link_color
- palette
- slider
- spacing
- spinner
- text
- typography

**Comment by dovy** [comment]
https://docs.redux.io/configuration/fields/output_variables.html

**Comment by andrejarh** [comment]
Hats off to you Dovy, for diving into this so quickly.

Css variables are solving the same thing as the output field, just in a more modern approach. I think fields which do not currently have an output option, don't need the output_variables. Soyour list of supported fields is just fine.

I've tested variables and they are already working. 
But I did notice some issues:

1.  DOCS:
I think the output border example is not correct.
https://docs.redux.io/configuration/fields/output_variables.html

The output I get is:
```
:root {
	--opt-header-border-border-color:#1e73be;
	--opt-header-border-border-style:solid;
	--opt-header-border-border-top:3px;
	--opt-header-border-border-right:3px;
	--opt-header-border-border-bottom:3px;
	--opt-header-border-border-left:3px;
}
```
Which works nicely.
According to the docs page, there should also be a parent output
```
:root {
	--site-header {
	    border-top    :3px solid #1e73be;
	    border-right  :3px solid #1e73be;
	    border-bottom :3px solid #1e73be;
	    border-left   :3px solid #1e73be;
	}
}
```
There is an issue with such output.
Variables in CSS are used as property values, But I have never seen using them as a selector as well and am not sure that will work. It made my scss preprocessor break when I fed it the example from the docs page. :) 

The type of aggregation which would work for borders is:
```
:root {
	--opt-header-border: 3px 3px 3px 3px solid #1e73be;
}
```
In css it could then be used like:
```
div {
	border: var(--opt-header-border);
}
```
The same aggregation would of course not work for all other fields.

2. I also tested typography field and noticed that the input is not correct

The field:
```
array(
    'id'          => 'content_font',
    'type'        => 'typography', 
    'title'       => 'Content Font Family',
    'font-backup' => false,
    'text-align' => false,
    'line-height' => false,
    'font-weight' => false,
    'color'       => false,
    'font-style'  => false,
    'font-size'   => false,
    'all_styles' => true,
    'default'     => array( 
        'font-family' => 'Source Sans Pro', 
    ),
    'output_variables' => true,
),
```
the output:
```
:root{
	--content_font-font-family:Open Sans;
	--content_font:font-family:"Open Sans";;
}
```
According to the docs, the output should be
```
:root{
	--content_font-font-family:Open Sans;
	--content_font {
		font-family:"Open Sans";
	}
}
```
notice that curly brackets are filtered out in the second line? This part wouldn't work anyway (as it contains CSS selectors). 

It might be a good idea to ditch the parent and just include the children, when the redux field is an array of fields - at least until the aggregation is defined on field-to-field basis.

**Comment by dovy** [comment]
Good call. I thought it worked like scss variables.  I’ll just ditch the parent and only leave the pieces. Is there any other way you’d like this improved?

**Comment by dovy** [comment]
Just did a push, give that a try. That will basically not output anything until we code the field by field example as you suggested.  ;)

**Comment by dovy** [comment]
Or rather, not output the parent item only until we proof and fix the output_variables for each and every field type.

**Comment by dovy** [comment]
Docs updated. This feature also added to the compiler hook allowing the appending of an array with the prefix variable use. IE, this feature will now serve CSS compilers as well as CSS variables.

https://docs.redux.io/configuration/fields/output_variables.html

**Comment by kprovance** [comment]
@dovy or @andrejarh , did this get resolved?

**Comment by dovy** [comment]
I am unsure, I never heard back.

**Comment by dovy** [comment]
@andrejarh Hey, you in? Did this get resolved?

**Comment by dovy** [comment]
Closing because it must be resolved.  ;)
