### ISSUE TITLE
Info field within Section (with Indent) issue

### ISSUE THREAD

**Issue by STV11C** [reduxframework/redux-framework-4#68]
## Support Hash
https://support.redux.io/?id=7X91%2FP605ikM1%2Bc0E5l6iLSR%2FLZqcW%2B%2Bbu2YIfVOGak8%2FzaOUycs7RhrZGSSUZewtmNGhEfPh%2FnYhV9DGAQ%2BZA%3D%3D

## Steps to reproduce
Place info field within a Section with indent. Example below:
```
array(
  'id' => 'section-tester',
  'type' => 'section',
  'title' => __('Section with Indent', 'redux'),
  'indent' => true 
),
array(
  'id'       => 'opt-test-info',
  'type'     => 'info',
  'style'    => 'info',
  'desc'     => __('An info field!', 'redux')
),
array(
  'id'       => 'opt-test-field',
  'type'     => 'switch',
  'title'    => __('A switch field', 'redux'),
  'default'  => true
),
```

## Expected Behavior
Info field to be indented and not break indent for following fields.

## Actual Behavior
Info fields breaks the indent flow of Section

## Any Error Details (PHP/JavaScript)
No

**Comment by kprovance** [comment]
After taking a close look at this, and verifying it was something that didn't wok in Redux 3, it appears that this will not be an issue easily overcome.  It has to do with the way those two fields hack the fieldset tables in the WordPress options API, specifically, both want to do so and they run into each other.  Even a JavaScript solution would be very complicated.

I'll stick this on the Redux Trello as something we're shelving to come back to at a later date.
