### ISSUE TITLE
Unable to subscribe to newsletter

### ISSUE THREAD

**Issue by alfredtakala** [reduxframework/redux-framework-4#72]
## Support Hash
https://support.redux.io/?id=egdHNXuPAoRXVlEhsVlD3%2FO3GHh8LVm3dWij1WB15QCQELQDorqupImCebTktAXb%2BAtc4oV7XEsnbarAnNRWmA%3D%3D

## Steps to reproduce
- Just installed Redux Framework 4 by downloading the source from this repository and upload to the wordpress.
- Activated the plugin and demo mode and that redirected me to wordpress/wp-admin/admin.php?page=redux_demo&tab=1, which showed "Welcome to the demo panel"
![Screen Shot 2019-12-24 at 1 22 40 AM](https://user-images.githubusercontent.com/53578896/71372003-156b0200-25ee-11ea-86d5-f46e99d42dcd.png)

## Expected Behavior
The actual and next steps for me to join the newsletter

## Actual Behavior
The new tab opened at https://news.redux.io/subscribe and shows API key not passed.
![Screen Shot 2019-12-24 at 1 18 37 AM](https://user-images.githubusercontent.com/53578896/71372057-3fbcbf80-25ee-11ea-949f-1023af58b4be.png)

**Comment by kprovance** [comment]
This feature has been removed from Redux 4 in the latest push.  We will have an alternative in the near future.
