### ISSUE TITLE
Metabox don't work

### ISSUE THREAD

**Issue by adrix71** [reduxframework/redux-framework-4#74]
Guys the metabox_lite extension has some problems because it doesn't work but there are no errors anywhere ... simply the metaboxes do not appear in the posts o pages.

I have tested with a clean install, new database, default WP theme and no other plugins.

The version is the one currently on github or 4.0.3

If it can be useful, the steps I have taken are as follows:

1) Download WordPress from wordpress.org ( current version 5.3.2)
2) Dowload ReduxFramework (current version 4.0.3)
3) Unzip WordPress inside my /home/myUser/www/reduxtest folder.
4) Unzip redux inside wp-content/plugins
5) Creating a dedicated VurtualHost inside my apache server.
6) Creating a new database inside mysql
7) Install WordPress and testing it.
8) Activate redux and embed demo.

A this point the theme options work, metabox no.

If they can be useful I give you some information about the system:

Apache: 2.4.29-1
MySQL: 5.7.29
PHP: 7.2.24

Some screen

![1](https://user-images.githubusercontent.com/14064365/74102806-52ac3480-4b47-11ea-9010-e96e46853cef.png)

![2](https://user-images.githubusercontent.com/14064365/74102812-5cce3300-4b47-11ea-91ec-86026191019e.png)

![Schermata del 2020-02-09 14-19-48](https://user-images.githubusercontent.com/14064365/74102841-8e46fe80-4b47-11ea-96b8-30945805c3cd.png)

![3](https://user-images.githubusercontent.com/14064365/74102846-930bb280-4b47-11ea-891c-f344392e23bd.png)

![Schermata del 2020-02-09 14-24-49](https://user-images.githubusercontent.com/14064365/74102901-fd245780-4b47-11ea-912d-e0984606ea23.png)

I'm sorry but I don't have more than that.

Have a nice Sunday
Adriano

**Comment by adrix71** [comment]
Add this comment to say that I have tried all the builds of the last year and the lincated one is the last one with working metaboxes. In all the following do not work.

I don't know what happened but it can be a starting point.

https://github.com/reduxframework/redux-framework-4/tree/7cae245792bd2280d69283d6572a37e790867961

Adriano

**Comment by adrix71** [comment]
I found the problem but the solution is beyond my reach.

When you renamed the class `class-redux-metaboxes-api.php` to `class-redux-api-metaboxes.php` you also added a `require_once` in the `Redux_Core` class (inside `register_classes()` method) but this is not enough because the method `check_extension_class_file()` in class `Redux` is still set up to do two things:

1) Look for classes with the suffix `-api` **after** the extension name and not **before** according to the new naming convention.

2) The variable `$class_name` is still valued to look for the classes that contain the bees inside the extension directories.

As proof you can put a simple line like the following

```php
echo "<pre>"; print_r( $api_check ); echo "</pre>";
```
before the loop
```php
if ( file_exists( $api_check ) && ! class_exists( 'Redux_' . ucfirst( $name ) ) ) {
```
you get this result or that the classes are searched with the wrong name in the wrong place.

![1](https://user-images.githubusercontent.com/14064365/74106770-a465b680-4b69-11ea-948f-807faa8eb919.png)

I also tried to rename the metaboxes bee class and put it back in the extension directory and it obviously works.


Adriano

**Comment by dovy** [comment]
@adrix71 great find! I'll take a look at it. My apologies for the delay, been on vacation with my fam. Care to hop on slack and chat this out sometime?

**Comment by adrix71** [comment]
Hi dovy no problem for delay ... and your right to take a vacation.

Yes I would like to chat. Fortunately now, compared to when we met a few months ago, work is taking up less and I have more time. 

Adriano

**Comment by Blackout8099** [comment]
I have fixed this for myself by changing 
```PHP
'class-redux-'. $new_name.'-api'
```
to
```PHP
'class-redux-api-' . $new_name ;
```

and adding 
```PHP
$api_check = str_replace( '/extensions/'.$name.'/', '/classes/', $api_check )
```
Below
```PHP
$api_check = str_replace( '-lite', '', $api_check );
```

**Comment by kprovance** [comment]
Metabox Lite has been removed.  Metaboxes will be available in the Pro version of Redux.  Sorry.
