### ISSUE TITLE
JS url error

### ISSUE THREAD

**Issue by szchengmi** [reduxframework/redux-framework-4#75]
When I put the core file reduxcore on my theme, the options interface in the background of Redux was in chaos. I checked that there were many JS not loaded normally!

Full and wrong URL address:
http://rgb.google.com/wp-content/plugins/www/wwwroot/rgb.google.com/wp-content/themes/demo/inc/ReduxCorev5/inc/fields/image_select/redux-image-select.js?ver=4.0.3.1582212819

**Comment by dovy** [comment]
Do you have a custom location for your wp-config or plugin folder?

**Comment by kprovance** [comment]
I am unable to recreate this.  Please provide a support hash (https://docs.reduxframework.com/core/generating-a-support-hash) as you may have a configuration that is affecting how the base URL is formed.
