### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework-4#78]
To make things clean, and to easily put the designs feature in here, let's rename `ReduxCore` to `redux-core`. Thoughts?

**Comment by kprovance** [comment]
I think it was a backward compatibility issue for older extensions?  Redux 4 and Pro can be modified to support that.  Not sure about older versions of extensions.

**Comment by dovy** [comment]
I'm pretty sure it's not an issue because people rename the directory all the time. I think we just never changed it.

**Comment by dovy** [comment]
Did it on my end.
