### ISSUE TITLE
Feature Request: Settings page locking

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-framework-4#8]
I'd like to request an option to enable locking for the settings pages, just like how WordPress does post locking.  I've been having issues with clients leaving the settings page open and never refreshing it, so when they make their daily update to a field and hit save, they're overriding everyone else's changes.

**Comment by kprovance** [comment]
We did a fundraiser for the feature once, some years back.  No one wanted to donate.  If we do this, it will strictly be for Pro.  We're not going to give away anything new anymore.  Redux v4 is it.  Everything after is premium.  :)

**Comment by kprovance** [comment]
I'm adding this to out internal Pro trello board.  I looked over the API WordPress uses for pages/posts.  Their API for this feature is geared toward pages/posts and presumably CPT.  It's based on the Heartbeat API and could be copied and modified for use with an option page.  But it's going to be a decent bit of work...and honestly, I want to begin getting paid for all this effort before I throw away anymore time on it.  If Pro does well after it's launched (no ETA on that) then I would be more amenable to spending time on it.  :)
