### ISSUE TITLE
Redux 3 & 4 Conflict

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework-4#82]
If both Redux 3 and Redux 4 are installed at the same time, things break. We have to find a way to fix this.

**Comment by dovy** [comment]
Solution: We'll check for Redux 3, if it exists do a disable on the plugin. If that works, great, if not display an error.

**Comment by kprovance** [comment]
Well, if the final release slug is going to be redux-framework (which is should for WP stat reasons), then both cannot be installed at the same time.
