### ISSUE TITLE
Border field CSS output not working

### ISSUE THREAD

**Issue by theme-x** [reduxframework/redux-framework-4#94]
I have migrated this version on my theme, everything working fine but border filed CSS output not working.

**Comment by dovy** [comment]
Let me get on this. We’ll have it solved soon.

**Comment by dovy** [comment]
Can you give me the config for your border field? I just tested and it's working fine for us...

**Comment by theme-x** [comment]
I used it for right border only and it was working fine on the old version, please check below.

Thanks
     

  'id'       => 'menu-item-seprator-border',
                    'type'     => 'border',
                    'title'    => esc_html__('Menu Item Separator Border', 'avas'),
                    'subtitle'    => esc_html__('It will show right border to separate.', 'domain'),
                    'desc'     => esc_html__( 'Enter border width ex: 1, 2, 3 etc to enable border. 0 to disable.', 'domain' ),
                    'output'   => array( '.main-menu > li' ),
                    'color'    => true,
                    'left'     => false,
                    'top'      => false,
                    'bottom'   => false,
                    'default'  => array(
                        'border-style'  => 'solid', 
                        'border-right' => '0px',
                        'border-top' => '0px',
                        'border-bottom' => '0px',
                    ),

**Comment by dovy** [comment]
Confirmed, found the bug. Thank you.

**Comment by dovy** [comment]
Fixed. Pull the newest version.  ;)
