### ISSUE TITLE
DevTools failed to load SourceMap: Could not load content

### ISSUE THREAD

**Issue by theme-x** [reduxframework/redux-framework-4#96]
Having console error on backend "DevTools failed to load SourceMap: Could not load content for" 
It seems missing Sourcemap file, please check the screenshot https://prnt.sc/su495r

Thanks

**Comment by dovy** [comment]
I'll take a look. These are usually a very easy fix. I'll have it resolved next week.

**Comment by dovy** [comment]
This should be also fixed in the new feature branch. Please verify.

**Comment by theme-x** [comment]
Default branch still same https://prnt.sc/t6plnq
Template still has few https://prnt.sc/t6pm3o

**Comment by dovy** [comment]
Confirmed no issues with dev_mode, so I think it's how you're using Redux. Can you please send me a copy of your code to dovy@redux.io? I will do testing on my end.

**Comment by dovy** [comment]
You can try out the newest build working without an issue here: 
https://swift-curlew.jurassic.ninja
User: demo 
Pass: 82ig5QeDA71M

So there may be a hook issue. Give it a try and let me know.

**Comment by dovy** [comment]
I believe this is fixed now from https://github.com/reduxframework/redux-framework-4/archive/redux-templates.zip

I have discovered why the menu items are hidden. Feel free to change your arg value of:
`'admin_theme'               => 'wp',`
to
'admin_theme'               => 'classic',

This will allow you to go to the old CSS styles which are working. I'll get the rest of the design issues resolved early next week.

**Comment by theme-x** [comment]
> This should be also fixed in the new feature branch. Please verify.

Still has one https://prnt.sc/t96yp7

**Comment by dovy** [comment]
Ha, I realized I had a .gitignore setting for .maps. Resolved in 3.1.8.  :)
